CREATE TABLE "NicheChannel" (
    "id" TEXT NOT NULL,
    "ytChannelId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "username" TEXT,
    "thumbnail" TEXT,
    "category" TEXT,
    "format" TEXT,
    "outlierScore" DOUBLE PRECISION,
    "isFaceless" BOOLEAN,
    "isAiChannel" BOOLEAN,
    "isMonetized" BOOLEAN,
    "quality" TEXT,
    "tags" TEXT[],
    "location" TEXT,
    "googleTrendsKeyword" TEXT,
    "createdAt" TEXT,
    "subscribers" INTEGER,
    "monthlyRevenue" DOUBLE PRECISION,
    "monthlyViews" INTEGER,
    "totalViews" INTEGER,
    "totalVideos" INTEGER,
    "avgViewsPerVideo" DOUBLE PRECISION,
    "avgVideoLength" DOUBLE PRECISION,
    "uploadsPerWeek" DOUBLE PRECISION,
    "rpm" DOUBLE PRECISION,
    "firstVideoDate" TEXT,
    "lastVideoDate" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "NicheChannel_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "NicheChannel_ytChannelId_key" ON "NicheChannel"("ytChannelId");
