export const DISPOSABLE_DOMAINS = new Set([
  // YopMail family
  'yopmail.com', 'yopmail.fr', 'cool.fr.nf', 'jetable.fr.nf', 'nospam.ze.tc',
  'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr', 'courriel.fr.nf',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'yopmail.pp.ua',
  'nospam4.us', 'yopmail.net', 'yop.email',

  // Guerrilla Mail family
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.info',
  'grr.la', 'sharklasers.com', 'guerrillamailblock.com', 'spam4.me',
  'jourrapide.com', 'dispostable.com',

  // TrashMail family
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.at',
  'trashmail.io', 'trashmail.xyz', 'trashmail.org', 'trash-mail.at',
  'trashmailer.com', 'trashmail.fr', 'trashmail.de', 'trashmail.eu',
  'mytrashmail.com', 'mt2009.com', 'mt2014.com',

  // Mailinator family
  'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator.us',
  'mailinator2.com', 'suremail.info', 'spamherelots.com', 'spam4.me',
  'binkmail.com', 'bobmail.info', 'chammy.info', 'devnullmail.com',
  'letthemeatspam.com', 'mailinater.com', 'mailinator.gq',
  'mailinator2.net', 'notmailinator.com', 'rtrtr.com',
  'tradermail.info', 'veryrealemail.com', 'zoemail.org',

  // 10 Minute Mail family
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '10minutemail.co.za', '10minutemail.de', '10minutemail.be',
  '10minutemail.nl', '10minutemail.ru', '10minutemail.pro',
  'minutemailbox.com', '10minemail.com', '10mail.org',
  '10minutemail.info', '10minutemail.us', '20minutemail.com',
  '20minutemail.it', '30minutemail.com', '2prong.com',

  // Temp-mail family
  'temp-mail.org', 'tempmail.com', 'tempmail.net', 'tempmail.de',
  'tempmail.co', 'tempmail.us', 'tempmail.ru', 'temp-mail.ru',
  'temp-mail.io', 'tempmail.io', 'tempinbox.com', 'tempinbox.co.uk',
  'temporaryemail.net', 'temporaryinbox.com', 'tempsky.com',
  'tempr.email', 'tempemail.co', 'tempemail.net', 'tempemail.com',
  'tmpmail.net', 'tmpmail.org', 'discard.email',

  // Throwaway email services
  'throwam.com', 'throwam.net', 'throwaway.email', 'throwam.net',
  'throwaway.io', 'discard.email', 'discardmail.com', 'discardmail.de',
  'spamhereplease.com', 'spamevader.com', 'mailexpire.com', 'spamex.com',
  'spam.la', 'spamfree24.org', 'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net', 'spamfree24.org', 'spamgob.com',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'antispam.de', 'spamoff.de', 'spambog.com', 'spambog.de',
  'spambog.ru', 'spamify.com', 'spamkill.info', 'spaml.com',
  'spaml.de', 'spammotel.com', 'spamspot.com', 'spamthis.co.uk',
  'spamthisplease.com', 'spam.su',

  // Maildrop / anonymous
  'maildrop.cc', 'mailnull.com', 'mailnesia.com', 'fakeinbox.com',
  'fakeinbox.info', 'fakemail.fr', 'fakemail.net', 'fakemailgenerator.com',
  'getairmail.com', 'filzmail.com', 'zetmail.com', 'maildu.de',
  'mailforspam.com', 'mailfreeonline.com', 'mailguard.me',
  'mailimate.com', 'mailme.gq', 'mailme.ir', 'mailme.lv',
  'mailme24.com', 'mailmetrash.com', 'mailna.biz', 'mailna.co',
  'mailna.in', 'mailna.me', 'mailnew.com', 'mailnull.com',
  'mailo.vc', 'mailpick.biz', 'mailproxsy.com', 'mailquack.com',
  'mailrock.biz', 'mailscrap.com', 'mailseal.de', 'mailshell.com',
  'mailsiphon.com', 'mailslite.com', 'mailtemp.info', 'mailtemp.net',
  'mailtome.de', 'mailtothis.com', 'mailzilla.com', 'mailzilla.org',

  // Wegwerfmail family
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'einrot.com', 'einrot.de', 'entick.com', 'ephemail.net',
  'e4ward.com', 'emltmp.com', 'ephemeral.email',

  // AirMail / other popular
  'airmail.cc', 'anonymbox.com', 'anonymmail.net', 'antispam24.de',
  'armyspy.com', 'azmeil.tk', 'beefmilk.com', 'binkmail.com',
  'bio-muesli.net', 'bobmail.info', 'bofthew.com', 'brefmail.com',
  'brennendesreich.de', 'bspamfree.org', 'bugmenot.com',
  'bumpymail.com', 'bund.us', 'buymoreplays.com', 'byom.de',
  'casualdx.com', 'cek.pm', 'centermail.com', 'centermail.net',
  'chogmail.com', 'choicemail1.com', 'clixser.com', 'cloakemail.com',
  'clrmail.com', 'cmail.club', 'cmail.com', 'cmail.net',
  'coinlink.com', 'cool.fr.nf', 'crazymailing.com', 'cust.in',
  'cuvox.de', 'dacoolest.com', 'daemsteam.com', 'dayrep.com',
  'deadaddress.com', 'deadletter.ga', 'deathmail.net', 'deeznode.com',
  'despam.it', 'devnullmail.com', 'dfgh.net', 'digitalsanctuary.com',
  'dingbone.com', 'disaq.com', 'discard.email', 'discardmail.com',
  'dodgeit.com', 'dodgemail.de', 'dodgit.com', 'donemail.ru',
  'dontreg.com', 'dontsendmespam.de', 'drdrb.net', 'dump-email.info',
  'dumpandfuck.com', 'dumpmail.de', 'dumpyemail.com', 'e-mail.com.ua',
  'e4ward.com', 'easytrashmail.com', 'edv.to', 'electro.mn',
  'email60.com', 'emailinfive.com', 'emailisvalid.com',
  'emailmiser.com', 'emailsensei.com', 'emailtemporanea.com',
  'emailtemporanea.net', 'emailtemporaneo.es', 'emailtmp.com',
  'emailure.net', 'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emailz.cf', 'emailz.ga', 'emailz.gq',
  'emkei.cz', 'emkei.ga', 'emkei.gq', 'emkei.ml', 'emkei.tk',
  'evopo.com', 'explodemail.com', 'express.net.ua', 'eyepaste.com',
  'fake-mail.ml', 'fake-mail.net', 'fakemailz.com', 'fakedemail.com',
  'falseaddress.com', 'fastacura.com', 'fastchevy.com', 'fastchrysler.com',
  'fastkawasaki.com', 'fastmazda.com', 'fastmitsubishi.com',
  'fastnissan.com', 'fastsubaru.com', 'fastsuzuki.com', 'fasttoyota.com',
  'fastyamaha.com', 'fdcserver.net', 'fightallspam.com', 'filbert7.com',
  'filipinolinks.com', 'fixmail.tk', 'fls4.gleeze.com', 'flyspam.com',
  'footard.com', 'fortunate.com', 'four.freeservers.com',
  'fr33mail.info', 'freemail.ms', 'freemail.tweakly.net',
  'freeml.net', 'freeplumbing.com', 'front14.org', 'fuckingduh.com',
  'fudgerub.com', 'fun2.biz', 'furzauflunge.de', 'fyii.de',
  'gardenscape.ca', 'garbagemail.org', 'gehensiemirnichtaufdiesack.de',
  'gelitik.in', 'get2mail.fr', 'getairmail.com', 'getmails.eu',
  'getonemail.com', 'ghosttexter.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'gladiator3d.com', 'gleeze.com', 'glitch.sx',
  'golfilla.info', 'gonex.ru', 'goodseller.co', 'gotti.otherinbox.com',
  'grandmamail.com', 'great.cz', 'gsrv.co.uk', 'gudanglowongan.com',
  'gustr.com', 'h.mintemail.com', 'h8s.org', 'haltospam.com',
  'hamham.uk', 'hazelnut.thebestwebmail.com', 'herp.in', 'hidemail.de',
  'high.estabbi.com', 'hopemail.biz', 'hotpop.com', 'hpc.tw',
  'hp.afro.com', 'hulapla.de', 'hupmail.com', 'ieatspam.eu',
  'ieatspam.info', 'ihateyoualot.info', 'iheartspam.org',
  'imails.info', 'inboxclean.com', 'inboxclean.org', 'infocom.zp.ua',
  'inoutmail.de', 'inoutmail.eu', 'inoutmail.info', 'inoutmail.net',
  'internet-e-mail.de', 'internet-mail.de', 'internetemails.net',
  'internetmailing.net', 'inwind.it', 'ipoo.org', 'iroid.com',
  'isnotmy.com', 'itcompu.com', 'ivyandlace.net', 'jetpay.com',
  'jnxjn.com', 'joliette.thebestwebmail.com', 'jonathanmanning.com',
  'junkmail.com', 'junkmail.ga', 'junkmail.gq', 'jupimail.com',
  'kasmail.com', 'keemail.me', 'keepmymail.com', 'killmail.com',
  'killmail.net', 'kimsdisk.com', 'klzlk.com', 'knol-power.nl',
  'kommunity.biz', 'konx.com', 'koszmail.pl', 'kurzepost.de',
  'l33r.eu', 'laoeq.com', 'lastmail.co', 'lazyinbox.com', 'letthemeatspam.com',
  'lhsdv.com', 'lol.ovpn.to', 'lookugly.com', 'lortemail.dk',
  'losemymail.com', 'lroid.com', 'lukop.dk', 'lukecarriere.com',
  'lukemail.info', 'lukeslymailer.com', 'm21.cc', 'mbox.re',
  'mega.zik.dj', 'megapathdsl.net', 'megapoint.com', 'migmail.net',
  'migmail.pl', 'migumail.com', 'miif.com', 'mintemail.com',
  'misterpinball.de', 'mmmmail.com', 'mobi.web.id', 'mohmal.com',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monkeytest.it',
  'monmail.fr.nf', 'mosaicfx.com', 'mox.pp.ua', 'msa.minsmail.com',
  'msft.cloudns.asia', 'mucincanon.com', 'mycleaninbox.net',
  'myemailboxy.com', 'myfastmail.com', 'myjunk.ih.ua',
  'mynetstore.de', 'mypacks.net', 'mypartyclip.de', 'myphantomemail.com',
  'mysamp.de', 'mysendalert.com', 'myspaceinc.com', 'myspaceinc.net',
  'myspaceinc.org', 'myspacepimped.com', 'mytempemail.com',
  'mytrashmail.com', 'nabuma.com', 'neomailbox.com', 'nepwk.com',
  'nervmich.net', 'nervtmich.net', 'netmails.com', 'netmails.net',
  'netzidiot.de', 'newfilter.ru', 'neverbox.com', 'nice-4u.com',
  'nincsmail.com', 'nl.szucsati.net', 'nnoway.ru', 'noblepioneer.com',
  'nomail.pw', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
  'nonspam.eu', 'nonspammer.de', 'noref.in', 'norseforce.com',
  'nospam.ze.tc', 'nospam4.us', 'nospamfor.us', 'nospammail.net',
  'notmailinator.com', 'ntlhelp.net', 'nullbox.info', 'objectmail.com',
  'odaymail.com', 'ohaaa.de', 'oin.email', 'okrent.us',
  'oneoffemail.com', 'oneoffmail.com', 'onewaymail.com',
  'onlatedotcom.info', 'online.ms', 'oopi.org', 'opentrash.com',
  'ordinaryamerican.net', 'otherinbox.comsafe.in', 'ourklips.com',
  'ourpreviewdomain.com', 'owlpic.com', 'ownsyou.de', 'ownmail.net',
  'oz.net', 'p71ce1m.com', 'paplease.com', 'payspade.com',
  'pchatz.ga', 'pecinan.com', 'pecinan.net', 'pecinan.org',
  'pepbot.com', 'phreaker.net', 'piauiemfoco.com.br', 'pickupmail.de',
  'pimpedupmyspace.com', 'pjjkp.com', 'plexolan.de', 'pml.com.ua',
  'pochta.ru', 'pookmail.com', 'pop3.xyz', 'postacep.tk',
  'postfach2go.de', 'privacy.net', 'proxymail.eu', 'prtnx.com',
  'prtz.eu', 'punkass.com', 'putthisinyourspamdatabase.com',
  'qisdo.com', 'qisoa.com', 'qoika.com', 'quickinbox.com',
  'r4nd0m.de', 'rainmail.biz', 'rcpt.at', 'reallymymail.com',
  'received.com', 'reconmail.com', 'recyclemail.dk', 'redfeathercrow.com',
  'rejectmail.com', 'rklips.com', 'rko.kr', 'rmqkr.net',
  'rn.com', 'rng.sytes.net', 'rocketmail.com.pn', 'ronnierage.net',
  'roubaixcamera.com', 'rppkn.com', 'rsvhr.com', 'rudymail.ml',
  'run.es', 's0ny.net', 's33db0x.com', 'safe-mail.net',
  'safetymail.info', 'safetypost.de', 'saynotospams.com',
  'sdfg.dk', 'sdf.org', 'sebil.com', 'send.hu', 'sendingspecialflyers.com',
  'sendspamhere.com', 'sfamo.com', 'sharklasers.com', 'shieldedmail.com',
  'shiftmail.com', 'shortmail.net', 'simaenaga.com', 'simpleitsecurity.info',
  'siteposter.net', 'skeefmail.com', 'slam.ru', 'slaskpost.se',
  'slippery.email', 'smellfear.com', 'smwg.info', 'snakemail.com',
  'sneakemail.com', 'sneakmail.de', 'snkmail.com', 'sofort-mail.de',
  'sogetthis.com', 'sohai.ml', 'soodomail.com', 'soodonims.com',
  'spam.care', 'spam.coroiu.com', 'spam.dnsx.eu', 'spam.email.ne.jp',
  'spam.fassagforlag.se', 'spam.gives', 'spam.hubei.net',
  'spam.la', 'spam.lol', 'spam.me', 'spam.og.pl', 'spam.ong',
  'spam.org.es', 'spam.ozh.ru', 'spam.pe', 'spam.ro', 'spam.su',
  'spam.to', 'spam.visuao.net', 'spam.wf', 'spambox.info',
  'spambox.irishspringrealty.com', 'spambox.me', 'spambox.org',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcon.org',
  'spamcorpse.com', 'spamday.com', 'spamdecoy.net', 'spameater.com',
  'spameater.org', 'spamfree.eu', 'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamgob.com', 'spamgoes.in', 'spamhero.com', 'spamhole.com',
  'spamify.com', 'spamkill.info', 'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com', 'spamoff.de', 'spamsalad.in',
  'spamslicer.com', 'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtrap.ro', 'spamtraps.net',
  'spamwc.cf', 'spamwc.de', 'spamwc.ga', 'spamwc.gq',
  'Speed.1s.fr', 'spikio.com', 'spr.io', 'ssoia.com',
  'startfu.com', 'startkeys.com', 'stealthmail.com', 'stexsy.com',
  'stinkefinger.net', 'storelatam.com', 'stuffmail.de', 'suburbanthug.com',
  'supergreatmail.com', 'supermailer.jp', 'superplatyna.com',
  'superrito.com', 'supersexepro.com', 'superstachel.de',
  'suremail.info', 'sute.jp', 'svk.jp', 'swissmail.net',
  'syosetu.x0.com', 'tafmail.com', 'tagyourself.com', 'takuyakimura.com',
  'tallpaul.com', 'tapchicuocsong.org', 'tapchidoanhnhan.org',
  'tddos.com', 'techemail.com', 'tele2.nl', 'tellos.xyz',
  'temp.emeraldwebmail.com', 'temp.mailboxy.fun', 'temp1.com',
  'tempail.com', 'tempalias.com', 'tempcloud.in', 'tempe.com',
  'tempemail.biz', 'tempemail.info', 'tempinbox.me', 'tempmail.co',
  'tempmail.de', 'tempmail.eu', 'tempmail.in', 'tempmail.it',
  'tempmail.plus', 'tempmail.pro', 'tempmail.space', 'tempmail.website',
  'tempmailo.com', 'tempomail.fr', 'temporaryemail.com',
  'temporaryemail.us', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymailaddress.com',
  'tempthe.net', 'testudine.com', 'thanksnospam.info', 'thanksnospam.net',
  'theinternetemail.com', 'thisisnotmyrealemail.com', 'throwit.email',
  'tilien.com', 'tittbit.in', 'tizi.com', 'tkenkyuukai.thebestwebmail.com',
  'tmailinator.com', 'toiea.com', 'tokuriders.club', 'toomail.biz',
  'topranklist.de', 'toss.pw', 'tr2k.com', 'trash-amil.com',
  'trash-mail.com', 'trash-mail.io', 'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashemails.de', 'trashmail.at', 'trashmail.com',
  'trashmail.io', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'trashmail.xyz', 'trashmailer.com', 'trashmail2.com',
  'trillianpro.com', 'trmailbox.com', 'trungtamtoeic.com', 'ttirv.org',
  'tuitmail.com', 'turual.com', 'twinmail.de', 'twoweirdtricks.com',
  'tyldd.com', 'ubismail.net', 'uggsrock.com', 'umail.net',
  'unmail.ru', 'upliftnow.com', 'uroid.com', 'uwork4.us',
  'vcmail.com', 'verkehrsknoten.de', 'veryrealemail.com', 'vidchart.com',
  'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net',
  'viewcastmedia.org', 'vkcode.ru', 'vomoto.com', 'vpn.st',
  'vps30.com', 'vps911.net', 'vsimcard.com', 'vubby.com',
  'wasteland.raptors.dk', 'watchever.biz', 'welikecookies.com',
  'wellhungup.dynu.com', 'wfgdfhj.tk', 'whyspam.me', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info',
  'wronghead.com', 'wuzupmail.net', 'www.e4ward.com',
  'wwwnew.eu', 'wyzwanie.agrikomi.com', 'x24.com', 'xagloo.co',
  'xagloo.com', 'xemaps.com', 'xents.com', 'xjoi.com',
  'xl.cx', 'xmaily.com', 'xmailer.be', 'xn--9kq967o.com',
  'xoxy.net', 'xwrqo.com', 'xyzfree.net', 'yanet.me',
  'yapped.net', 'yeah.net', 'yentzschpark.com', 'yep.it',
  'yogamaven.com', 'yopmail.com', 'yopmail.fr', 'yopmail.fr.nf',
  'yopmail.net', 'youmail.ga', 'youremailsucks.com', 'yourlms.biz',
  'zehnminutenmail.de', 'zoemail.net', 'zoemail.org', 'zomg.info',
  'ztcdns.com', 'zxcv.com', 'zxcvbnm.com', 'zzi.us',

  // Common burner/anonymous services
  'anonymousemail.me', 'anonymail.net', 'anonymbox.com',
  'anonimize.email', 'anoninbox.com', 'anon.email',
  'nobodyhere.com', 'mailnew.com', 'meltmail.com',
  'noclickemail.com', 'notsharingmy.info', 'nowmymail.com',
  'nsk.com.ua', 'objectmail.com', 'odnorazovoe.ru',
  'oneoffemail.com', 'onetimefakemail.com', 'onewaymail.com',
  'orangatango.com', 'otherinbox.com',

  // Additional Russian/Eastern European disposables
  'discard.ga', 'discard.gq', 'discard.ml',
  'gero.us', 'gomail.in', 'gotmail.com', 'gotmail.net', 'gotmail.org',
  'grn.cc', 'gtmlabs.com', 'guerrillamail.net',
  'hacccc.com', 'hackersquad.tk', 'hailmail.net', 'hanmail.net',
  'hasegawa.thebestwebmail.com', 'hatespam.org', 'hawrych.pl',
  'helpinghandtaxcenter.org', 'herreramail.com', 'hezll.com',
  'hidebirthdaygifts.com', 'hidemail.de', 'hidemail.pro',
  'hmamail.com', 'hochsitze.com', 'hopemail.biz', 'hostcalls.com',
])

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim()
  if (!domain) return true
  return DISPOSABLE_DOMAINS.has(domain)
}
